---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: docker://lpenz/omnilint:0.5.1
  python:
    uses: lpenz/ghworkflow-python/.github/workflows/python.yml@v0.4.0
    with:
      coveralls: true
      deb: true
      publish_pypi: true
      publish_github_release: true
      publish_packagecloud: true
      publish_packagecloud_repository: |
        ["debian/debian/bullseye",
         "debian/debian/bookworm",
         "ubuntu/ubuntu/kinetic",
         "ubuntu/ubuntu/focal"]
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build
      - run: nix flake check
  publish-cachix:
    needs: [ omnilint, python, nix ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.11.0
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          skipPush: ${{ steps.version.outputs.version_commit == '' }}
          name: lpenz
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build
      - run: nix flake check
