---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: docker://lpenz/omnilint:0.5.1
  python:
    uses: lpenz/ghworkflow-python/.github/workflows/python.yml@v0.4.0
    with:
      coveralls: false
      deb: false
      publish_pypi: true
      publish_github_release: true
      publish_packagecloud: false
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
